From bleakie/cuda10.2_cudnn8.0_ubuntu16.04
USER root

RUN apt update

RUN apt-get -y install wget

# install openmpi
ENV OPENMPI_VERSION=4.0
ENV OPENMPI_STRING=openmpi-${OPENMPI_VERSION}.0
RUN mkdir /tmp/openmpi && \
        cd /tmp/openmpi && \
        wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.0.tar.gz && \
        tar zxf ${OPENMPI_STRING}.tar.gz && \
        cd ${OPENMPI_STRING} && \
        ./configure --enable-orterun-prefix-by-default --with-openib --prefix /usr/local/mpi && \
        make -j 4 all && \
        make install && \
        ldconfig && \
        rm -rf /tmp/openmpi && \
        test -f /usr/local/mpi/bin/mpic++  # Sanity check
ENV PATH /usr/local/mpi/bin:$PATH

RUN apt-get -y install git
# ENV all_proxy=socks5://gauss:11955
RUN git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime && sh ~/.vim_runtime/install_awesome_vimrc.sh
RUN echo "set number" >> ~/.vimrc
RUN apt-get install less
RUN pip3 install gpustat
RUN pip3 install mpi4py


RUN git clone https://github.com/espnet/espnet.git
WORKDIR espnet
# RUN git config --global  --unset https.https://github.com.proxy
# RUN git config --global  --unset http.https://github.com.proxy
RUN ./ci/install_kaldi.sh
WORKDIR tools
ENV CONDA_TOOLS_DIR `dirname ${CONDA_EXE})/..`
RUN touch activate_python.sh && chmod +x activate_python.sh
RUN apt-get -y install cmake && apt-get -y install sox && apt-get -y install libsndfile1-dev && apt-get -y install ffmpeg
RUN make TH_VERSION=1.8.0 CUDA_VERSION=10.2
# RUN sed -i "s/\(echo.*CUDA\)/#\1/" setup_cuda_env.sh
# RUN . ./setup_cuda_env.sh /usr/local/cuda
#ENV CUDA_HOME /usr/local/cuda
#ENV PATH $CUDA_HOME/bin:$PATH
#ENV LD_LIBRARY_PATH $CUDA_HOME/lib64:$LD_LIBRARY_PATH
#ENV CFLAGS "-I$CUDA_HOME/include $CFLAGS"
#ENV CPATH $CUDA_HOME/include:$CPATH
#ENV CUDA_PATH $CUDA_HOME
# RUN git config --global  --unset https.https://github.com.proxy
# RUN git config --global  --unset http.https://github.com.proxy
# RUN ./installers/install_warp-transducer.sh
# RUN git clone https://github.com/b-flo/warp-transducer.git && cd warp-transducer/ && mkdir build && cd build && cmake -DCUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME .. && make && cd pytorch_binding && python setup.py install

WORKDIR /workdir

CMD ["bash"]
